### ISSUE TITLE
White Flash while using Google search

### ISSUE THREAD

**Issue by freelze** [overdodactyl/ShadowFox#125]
* screenshots (GIF) : https://imgur.com/Vd66g90

* browser version : stable

* operating system : windows

* explicit instructions how to get to the broken feature/webpage :
  Whenever I using google search , white flash pop for almost 0.1 second

* how you are using ShadowFox (complete userChrome/Content, userChrome/userContent_imports, gulp) :
  complete userChrome/Content

**Comment by overdodactyl** [comment]
Hi @freelze.  This appears to be an external issue caused by something other than ShadowFox.  

ShadowFox doesn't alter webpages (with a few exception like addons.mozilla.org), and it looks like the flash you are seeing is actually Google's "normal" white styling.  

What are you using to obtain the dark look on Google?  I would recommend using an extension like [Stylus](https://addons.mozilla.org/en-US/firefox) and a userstyle for the website.  You can check out some for Google here:

https://userstyles.org/styles/browse?search_terms=google

**Comment by freelze** [comment]
Thank for your reply.
But I've already use xStyle , same as stylish, and Dark Background and Light Text add-on.
The white flash still exist.
I would try stylish tomorrow.

**Comment by overdodactyl** [comment]
If you're using a dark userstyle for a webpage, make sure to disable Dark Background and Light Text for that site
