### ISSUE TITLE
Theme for Downloads sidebar

### ISSUE THREAD

**Issue by Nightliss** [overdodactyl/ShadowFox#177]
Name: Downloads sidebar 
Link: https://addons.mozilla.org/en-US/firefox/addon/downloads-sidebar/

What needs to be styled:

![ss](https://user-images.githubusercontent.com/30467858/42417389-fb37a5aa-8288-11e8-8650-53dface500ff.JPG)

Also a question: How can I inspect the sidebar to get class names of the elements there? I could probably style it myself but default inspector doesn't go outside main browser window and googling for an answer didn't yield any result :/

**Comment by overdodactyl** [comment]
Hi @Nightliss, I've added a theme for the extension if you want to update.  It's not one I use, so if there's things I've missed or it breaks in future versions, feel free to re-open/open a new issue.

>How can I inspect the sidebar to get class names of the elements there

For extensions the easiest way I've found is to use the "Debug" feature:

- `about:debugging#addons` or, alternatively, `about:addons` > Gear Menu > "Debug Addons"
- Find the add-on of interest and select "Debug".  

This will bring up the inspector, but instead of inspecting browser elements, you can inspect the add-on.

You can use the button in the top right (square button, top half rectangle, bottom half two squares) to target a specific iframe.  For example, to target the addons sidebar, change focus to `moz-extension://......./sidebar/panel.html`
