### ISSUE TITLE
Shadowfox darkens iframes

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#182]
I don't know how it happens, but shadowfox darkens iframes on amazon.
Probably something with the now deprecated `@-moz-document` rules.

Example:
https://www.amazon.de/dp/B07FWSFNHZ/

![](https://i.imgur.com/IaIIvWf.png)

Guilty seems to be `html:not(#ublock0-epicker) body:not(.ze_body)` from `about_pages.css`.

FF bug?

FF61.0.1

**Comment by overdodactyl** [comment]
Hi @stonecrusher - 

iframes have been giving me issues and I haven't yet found a great workaround for.  The rule you mentioned is the root cause, and it's there to prevent white flashes.  Unfortunately, it also effects any website that doesn't specify the iframe's background color. 

I hadn't yet come across this on a site as large/popular as Amazon however.   

Both of the `:not(..)`'s mentioned are more hacky workarounds than anything (one for uBO and the other for the site zoho notebook from #181).  On sites that don't give the iframe a class name/id, I'm not sure of a workaround either (such as Remember the Milk in #167).

I'll for a better solution, but if anyone has any ideas, it would great!

**Comment by stonecrusher** [comment]
Do you have an example of a white flash for me to test?

**Comment by overdodactyl** [comment]
I believe the new tab page was an example that showed a white flash after removing that line

**Comment by stonecrusher** [comment]
We need to target FF specifically, not the whole web.
As `@-moz-document` seems not to work for this, we need to use properties distinct to FF.

Try something like
```CSS
  html[dir="ltr"][lang],
  html[dir="rtl"][lang],
  html[dir="ltr"][lang] body,
  html[dir="rtl"][lang] body
```
instead of
```CSS
:not(.ze_area) > html,
html:not(#ublock0-epicker) body:not(.ze_body)
```

Note that I didn't test whatever the `.ze_...` fixes.
uBO works perfectly.

Also I am not sure what a `* > html` selector should do. Probably iframe-related. You can add the `* > ` if you want.

**Comment by overdodactyl** [comment]
Thanks again and sorry for the delay.  Your suggestion was implemented, let me know if you run across this anywhere else!
