### ISSUE TITLE
Request for Chrome Store Foxified dark theme

### ISSUE THREAD

**Issue by tzimon** [overdodactyl/ShadowFox#205]
Name: Chrome Store Foxified
AMO Link: [https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/)
What needs to be styled: the moz-extension:// page

**Comment by overdodactyl** [comment]
I've applied the available "generic styling" to the add-on since it seems pretty basic. At a quick glance, it seems to work fine. 

Please keep in mind that since I don't use this add-on, there might be some things I missed or there may be breakage in the future I won't know about unless notified. If that's the case, please re-open this issue or open a new one
