### ISSUE TITLE
Request: FF Android support

### ISSUE THREAD

**Issue by ChristoferMinestar** [overdodactyl/ShadowFox#217]

**Comment by overdodactyl** [comment]
Hi there @ChristoferMinestar - 

Thank you for the suggestion, but I don't think this will be possible.  It appears Android doesn't support `userChrome.css` and `userContent.css`, and there isn't any kind of replacement.

Additionally, since the browsers are so different on mobile and desktop, I would be surprised if any of the code in this repository could be repurposed.  This, in addition to me being an iOS user, would likely make a separate project a better option if it ever became possible on Android.
