### ISSUE TITLE
checkbox not legible on SSL error page & Firefox container addons settings

### ISSUE THREAD

**Issue by nirojanv** [overdodactyl/ShadowFox#219]
OS: macOS 10.14.1
Browser version: Beta 64.0 b8
CSS: Almost stock shadowfox css except for additional css to hide vertical tabs in favour of vertical tabs using tree style tabs addon and hide the title bar for sidebar.

The report errors checkbox on SSL error page is currently checked but it is hard to work out if it is or not without looking for corresponding `about:config` variable. The checkbox to always open the website on certain container is also not legible.

Also, there is a white space on the side which I believe is caused by multi container addon as other addons that I have in overflow menu don't have this issue. Not sure if anything can be done about that.

Test url: https://self-signed.badssl.com or any link with exclamation mark on this page - https://badssl.com/

![image](https://user-images.githubusercontent.com/22147724/48410301-216f6980-e736-11e8-8ad4-ec53e19e3381.png)

Also the checkbox on firefox container page asking whether to open the website on assigned container has the same issue.

![image](https://user-images.githubusercontent.com/22147724/48410743-72339200-e737-11e8-966a-90d15d54c323.png)

Thanks

**Comment by overdodactyl** [comment]
Hi @nirojanv, thanks for opening the issue!

The checkboxes on SSL error pages and the container page should be fixed.

The background for multi-account-containers is no longer white, but it looks a little off because MAC doesn't utilize the whole overflow area.  It looks like there are plans to fix this on their end:

`https://github.com/mozilla/multi-account-containers/issues/1268`

The checkbox in the popup seems to be an issue with multi-account-containers itself:

`https://github.com/mozilla/multi-account-containers/issues/1306`

**Comment by nirojanv** [comment]
Thank you for fixing the issue.

At least the overflow area for MAC isn't white which is great and makes it a bit more consistent with dark colour everywhere else.

They are planning to get someone full time between December & March time frame to go through prioritised issues & feature requests. Hopefully they can get someone working on MAC, as it is a great addon with lot of potential. https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-434534754

**Comment by overdodactyl** [comment]
I agree, it's a great add-on with a lot of potential to grow.

I think I fixed what I can on my side, so I'm going to go ahead and close this; feel free to re-open if I've missed something.

Thanks again for the detailed bug report, it's really appreciated!
