### ISSUE TITLE
I don't understand how to install this

### ISSUE THREAD

**Issue by pleasejust** [overdodactyl/ShadowFox#225]
I don't understand what is going on here. I go to the website, click on the appropriate link (macosx64) -- unrelated, I don't understand why there is a macos x32 version? Who is that for? Is it for powerPC systems? I've only seen that denoted as PPC -- anyways, the file is shadowfox_mac_x64. I double click on it and it opens in textedit. I apply chmod -x to the file. Still opens in textedit. Nowhere in the instructions does it even say what to do with the file. I found reply in a topic which says you should be able to double click on it. Well that doesn't work. Shadowfox readme tell me to go to shadowfox-updater readme which leads me to the same shadowfox_mac_x64 file.... so I install the updater using homebrew method... ok, done, installed now what? Restart firefox... nothing.. am I supposed to be looking for something? A setting somewhere?

**Comment by overdodactyl** [comment]
>Nowhere in the instructions does it even say what to do with the file

It can be run in the same manner as most scripts from terminal: `./<file_path>`

> so I install the updater using homebrew method... ok, done, installed now what?

You can run `shadowfox` from the command line, select your options, run it, and then restart Firefox:

https://github.com/SrKomodo/shadowfox-updater/blob/master/README.md

Closing in favor of your other issue (https://github.com/SrKomodo/shadowfox-updater/issues/29), since this is related to the installer.

**Comment by SrKomodo** [comment]
Also, you said that you applied `chmod -x` to the file, but the readme states you should apply `chmod +x`
