### ISSUE TITLE
turn off shadowfox

### ISSUE THREAD

**Issue by 20NE** [overdodactyl/ShadowFox#240]
Gratefull for this great project. Thx
Is there a way to turn off shadowfox temporarily?

**Comment by adamwinn** [comment]
I'd love to know this as well.  I'd like the normal light theme during the day and then Shadowfox at night.

**Comment by overdodactyl** [comment]
The biggest issue here is that in order to update modifications to `user*.css` files, Firefox has to be restarted.

@SrKomodo, how does the updater handle user customizations when uninstalling/installing? Does it keep them or do they get removed? I'm wondering if simply using the uninstall/install options in the updater could essentially act as a solution here.

If this does work, @adamwinn, since the updater can be run via the command line, you could write a simple script to run at certain times of the day (you'd have to decide how you wanted to handle the FF restart though).

**Comment by SrKomodo** [comment]
Currently, the updater removes the customizations folder when uninstalling, but i think im gonna change that so that it keeps them, that way you can uninstall and reinstall and the customizations should persist.

**Comment by overdodactyl** [comment]
Sounds good, thanks!

And @20NE and @adamwinn, if you don't have any customizations, the install/uninstall method seems like it would be a decent solution currently since it's a quick process

**Comment by 20NE** [comment]
OK，thx for the tips

**Comment by SrKomodo** [comment]
The latest version no longer removes the customizations folder when uninstalling, so this issue can be closed

**Comment by 20NE** [comment]
closed
