### ISSUE TITLE
Themeing #onboarding-overlay

### ISSUE THREAD

**Issue by Mattwmaster58** [overdodactyl/ShadowFox#33]
Could we theme it? The only thing that might be an issue is the images. 
Currently the onboarding overlay looks like this:
![capture](https://user-images.githubusercontent.com/26337069/34071991-c15aa086-e23c-11e7-9b5e-dd9703c05145.PNG)

**Comment by overdodactyl** [comment]
Thanks! I'll get that themed :)

**Comment by Mattwmaster58** [comment]
Looks good except for some inconsistencies in icon color and skip tour button
![index](https://user-images.githubusercontent.com/26337069/34133687-6b96ecbc-e413-11e7-8b5b-95e388993a7f.png)
, refer to the screenshot below.

**Comment by overdodactyl** [comment]
Looks like those icons are, by default, a different color.  It only becomes more noticeable with a dark background.

Since the icons are used as background images, they can not be individually styled/filled with a different color.

I could download the icons, modify them, upload the new icons to the repo and reference them....however given the how unlikely it is for users to frequent this page, I'm not entirely convinced it's worth it
