### ISSUE TITLE
Some missing styling

### ISSUE THREAD

**Issue by azizLIGHT** [overdodactyl/ShadowFox#35]
I saw some missing styling:

1) about:addons home page content area (I got there by going to about:about and clicking about:addons there) has a white background:
![image](https://user-images.githubusercontent.com/8013867/34073645-d4205ef2-e26b-11e7-9596-6b8edfb34214.png)

2) about:addons legacy extentions page's "find a replacement" buttons used to be styled blue, but are now grey. Also, the other buttons for remove, and more are also grey and its not clear whether they can be interacted with or not. The entire screen seems to have some shading on top of it thats graying out the blue and white/grey text
![image](https://user-images.githubusercontent.com/8013867/34073670-7b4e7470-e26c-11e7-82e4-bf9933518b2d.png)

3) about:healthreport has no styling:
![image](https://user-images.githubusercontent.com/8013867/34073655-1546d21c-e26c-11e7-8cab-7f4526f7a7be.png)

**Comment by overdodactyl** [comment]
Thanks - I'll look into these when I get a chance.

**Comment by azizLIGHT** [comment]
One more on the new tab page, bottom right of recommended by Pocket, the text there in the corner is partially styled by the old darkcyan instead of blue-50 blue-60 (or blue-40):  
![image](https://user-images.githubusercontent.com/8013867/34075187-cf935f76-e28c-11e7-95a6-50f6798a60e8.png)

**Comment by overdodactyl** [comment]
Hi @azizLIGHT,

1.  I'm not presented with the about:addons home page you have a screen shot of no matter how I access it.  I'm thinking it might just be present if you don't have any addons installed, in which case I'm not too concerned about it.

2.  The legacy page probably appears to have a gray shading over it because all the addons are disabled.  You will see the same styling with disabled addons in the normal section. I don't have any legacy addons installed, so I can't get to this page (nor can you install old legacy extensions).  I don't want to spend too much time on this page given Firefox no longer supports these addons and the page essentially no longer has any value and will likely be removed in a matter of time.

3.  `about:healthreport` has been styled.

4. The text you mentioned has now been changed.

Thanks for bringing these to my attention.

**Comment by azizLIGHT** [comment]
Fair enough! Thank you!
