### ISSUE TITLE
uBlock Origin dark theme

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [overdodactyl/ShadowFox#42]
discussion continued from https://github.com/gorhill/uBlock/issues/3342

sample from @overdodactyl with a a couple of original colors pasted in
![lightenupbro](https://user-images.githubusercontent.com/16656956/34315871-707e542c-e7ec-11e7-93ed-0f0cd37f0908.png)

- red/green/ (and yellow I assume) seem way too dark. Nothing wrong with the original colors
- grey colors - obviously we can;t use grey anymore, but please do not use red if you are (it's a bit confusing to me if this is happening or not) - use shades of blue (use the same saturation/luminosity etc as red, just switch around the RGB values to get the two shades (light/dark)
- color blind version needs testing

**Comment by overdodactyl** [comment]
Thanks @Thorin-Oakenpants! 

Thanks for the ideas! I was definitely a bit too hast getting a first draft up on the repo.

I agree the colors are too dark.  I used a similar color, but neglected to account for the opacity in the original ones onto the white background.  

Blue's a good idea to replace grey with (it's not in the screenshot, but I had a lighter grey that blended in a little too well)

Also neglected to look at color blind version...back to work!

**Comment by overdodactyl** [comment]
Here's a look with the same red and green colors and blue instead of grey:

![colors](https://user-images.githubusercontent.com/33071129/34317245-644d6c6e-e7a2-11e7-96f1-d6ed48bb630c.png)

**Comment by Thorin-Oakenpants** [comment]
> but neglected to account for the opacity

That's what I originally suspected/said in the other comment, but I edited that post to just point to here. That all looks good. Don't forget that yellow one :)

PS: I just turned on color blind friendly and I have no idea (they're all too close for my eyes). I think you will want some help with that. There are PS filters for testing the three main types (I have one somewhere, so sing out if you need it). From ages ago all I remember is that blue-color-blindness is rare (1%) and only affects men (yay for them!), The main one is red-green. **Maybe ask on reddit so you can pimp yourself again xD** :)

**Comment by overdodactyl** [comment]
Got the yellow one covered :)

I'll play around with the color blind friendly version a bit, but you're probably right about needing help with that one.  If I can't find the PS filters, I'll let you know, thanks! Nothing ever seems to be easy ¯\_(ツ)_/¯

Haha and when in doubt, always turn to Reddit :P

**Comment by Thorin-Oakenpants** [comment]
Well TBH the PS filter I have from around 16 (sixteen!!) years ago (so may not work in your PS version) simply shows you what the colors would look like if you were X type of color blind. I used it more for changing the colors used, so no color-blind friendly option was needed. Here we just need to make sure the colors in the friendly version don't change (I think, since they lack red/green)

Just had a look around and I think I ditched that plugin in some purge years ago. We've come along way in 16 years .. there are online color simulators - http://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by Thorin-Oakenpants** [comment]
checkin' needed - did you cover the 6 colors in the mouseover in the cells

![mouseymousey](https://user-images.githubusercontent.com/16656956/34318877-dafec62a-e836-11e7-9ac4-56efd7f63893.png)

**Comment by overdodactyl** [comment]
Thanks for that website @Thorin-Oakenpants! Had a little too much fun just playing around with that and uploading different photos haha.

Since I'm using the same colors as uBO (when taking into account opacity), I think I should be able to just do the same thing for the color blind friendly version and not have to worry too much.  

In the original version I posted I had not done the hover colors, but they are now taken care of as well :)

**Comment by Thorin-Oakenpants** [comment]
Excellent ... you may take the day off tomorrow :)

**Comment by Thorin-Oakenpants** [comment]
rather than add a new issue...
https://raw.githubusercontent.com/overdodactyl/ShadowFox/master/userContent-files/webextension-tweaks/decentraleyes.css

double `;` at end of `header, .panel:not(:last-child)`

**Comment by overdodactyl** [comment]
Good catch @Thorin-Oakenpants, thanks! All fixed :)

**Comment by Thorin-Oakenpants** [comment]
Hmmm .. so I thought I might darken a few things - I'm not using anything except some tweaks to my speed dial extension and a couple of chrome changes (removed context menu items etc)

to userContent I added the root item variables and then the uBo css contents, and I still don't get the original colors (eg as per pasted in the first pic). Is there some opacity setting that needs applying?

**Comment by overdodactyl** [comment]
Welcome to the dark side! :)

I just made a slight change for the sidebar colors to lighten them up a bit, but didn't change the main ones.  Instead of using uBO's original colors and having to deal with finding the right opacity, I took a screenshot and used PS to get the hex color and used an opacity of one.  It seems to be a pretty good match for me.  Here's with and without styling (I think I have all the colors in here):

![Light](https://user-images.githubusercontent.com/33071129/34375456-85ff91c2-eade-11e7-8d0e-af71f2e3cc8c.png)

![Dark](https://user-images.githubusercontent.com/33071129/34375465-8d4f861c-eade-11e7-881f-dda03438ecec.png)

The colors admittedly look different in those screenshots, but I think it's partially an optical illusion from having a dark vs. light background.  

If they are overlayed on one another, it seems to be a decent match: 


![overlay](https://user-images.githubusercontent.com/33071129/34375594-3c478c00-eadf-11e7-86d6-672b34002814.png)

I'll keep playing with it, but I don't think it's tooo far off.  Is this different than what you're seeing?

As for the bottom column, I have no clue what could be causing that! I'll see if I can figure something out, but it's bizarre it's happening for only some (maybe an odd OS quirk?)

**Comment by Thorin-Oakenpants** [comment]
Yeah .. I'm not getting those colors at all - maybe tomorrow I will pastebin you the code I added - everything is so dark on dark

**Comment by overdodactyl** [comment]
Feel free to send me a pastebin!

If you don't want to post it on here, I can give you an email or something of the sort

**Comment by Thorin-Oakenpants** [comment]
no need to leave this open .. I'll sort out using **some** shadowfox stuff down the track when I have time :) I've actually become accustomed to light panel dropdowns (on my mostly dark webpages) where the contrast is better - also, I al soooo used to uM and uBo colors etc and I rely on and use these extensions **A LOT**

**Comment by overdodactyl** [comment]
Makes sense! Feel free to let me know at any point down the road if there are any issues you come across that need to be addressed :)

I uploaded a "first draft" of uMatrix yesterday (still needs a little playing with), but interestingly the matrix colors were not at all effected by a darker background, so luckily I didn't even have to touch those (and there's no gray noops to deal with either).

**Comment by Belmaj** [comment]
> Makes sense! Feel free to let me know at any point down the road if there are any issues you come across that need to be addressed :)
> 
> I uploaded a "first draft" of uMatrix yesterday (still needs a little playing with), but interestingly the matrix colors were not at all effected by a darker background, so luckily I didn't even have to touch those (and there's no gray noops to deal with either).

hello sir can i ask how to apply dark theme in ublock origin im using chrome can you answer my question sir?
