### ISSUE TITLE
Can't get ShadowFox to work

### ISSUE THREAD

**Issue by Antinatalist** [overdodactyl/ShadowFox#47]
Hello,

I downloaded files, placed them accordingly... and nothing happened.
What has gone wrong?
Thanks in advance.

Cheers

**Comment by overdodactyl** [comment]
HI @Antinatalist,

Can you be a little more specific about what you've tried (what files you've added, where you've placed them, what other `*.css` tweaks you are using etc.).

Have you looked through this guide?

https://github.com/overdodactyl/ShadowFox/wiki

Also, it's worth noting changes won't go into effect until you restart your browser.

**Comment by philkoch** [comment]
I have a similar problem. I downloaded `userChrome.css` and `userContent.css` and put them into `~/.mozilla/firefox/3nzsg9nc.default/chrome`. Then I restarted the browser but everything looks like before. I'm using Firefox-Nightly 59.0a1 (2017-11-14) (64-bit) on an Arch Linux machine.
Thanks

**Comment by overdodactyl** [comment]
Hi @philkoch,

Just a few quick sanity checks before we go too far:

(1) Are you sure that is the correct profile? Some users create multiple profiles and their default isn't actually the one labeled `...default`.

You can double check by doing the following:

* Visit `about:support` by entering this address in the url bar.

* Scroll down to `Application Basics`.

* In the `Profile Folder` section, click the button that says "Open Folder", "Show in Finder" or "Open Directory" (OS dependent).

* Check to make sure you have your chrome folder with the two files located here

(2) When you say everything looks like before, is there nothing at all styled?  To get the main nav-bar area styled, you will need to use FF's built in dark theme (Hamburger Menu>Customize>Themes>Dark.

A few places to check if anything's taking place:

* Hamburger Menu 

* Sidebar

* `about:addons`

**Comment by philkoch** [comment]
Hi @overdodactyl,
thanks for looking into this.
Yes, I made sure that I use the profile folder that is the one from the `about:support` page. I used the Dark-Theme before I tried installing ShadowFox, but unfortunately the nav-bar is the only part that is dark. The hamburger menu and sidebar is still the default Firefox theme.
I also checked `about:profiles` and added the chrome folder also in the `~/.cache/mozilla/firefox/..` profile, but without success. I found a thread on [Reddit](https://www.reddit.com/r/firefox/comments/6s2ol8/why_userchromecss_is_not_working_in_nightly/), describing that the css files don't work in nightly. 
I also tried disabling multiprocess-windows, since this seems be a possible problem. I de-activated it, but it didn't help.

**Comment by philkoch** [comment]
Hi @overdodactyl,
embarrassing to say this, but it seems like something went wrong with my downloads of the files. They were empty. Unfortunately I only checked the paths and filenames. I re-downloaded the files and now it works.
Sorry for wasting your time.

**Comment by overdodactyl** [comment]
It's no trouble at all @philkoch, I'm glad you got it working!

@Antinatalist, is something similar possibly happening in your case?

**Comment by overdodactyl** [comment]
Closing for now, but feel free to ask any followups should they be necessary
