### ISSUE TITLE
Can't see changes to the extensions.

### ISSUE THREAD

**Issue by WovenTide** [overdodactyl/ShadowFox#51]
Hello !

First i want to thank you for your amazing work. 
I only have one problem, and it may be because I am a total noob, so I hope I won't bother you too much with my problem.

I copied every files from shadowfow-master to the chrome folder of my profile but I can't see any changes to Ublock / decentraleyes etc. Everything else is working perfectly.

Should I do a specific manipulation ? 

I hope you have a nice day !

**Comment by overdodactyl** [comment]
Hi there! 

I'm glad you're enjoying the project :)

Unfortunately for the webextensions each user will have to make a specific change because the only way to edit them is through using their Internal UUID (which varies for every install).

Please see here for more info, and feel free to let me know if you have any further questions!

https://github.com/overdodactyl/ShadowFox/wiki/ShadowFox-is-incompatible-with-the-preferences-page-of-one-of-on-my-addons#workaround

I need to update the wording to reflect the current state of the repo (at the time it was written, I was only making modifications to extensions that ShadowFox "broke", not adding dark themes to ones like uBO), but the basic info is all the same

**Comment by overdodactyl** [comment]
Closing for now, but feel free to ask any followups should they be necessary :)

**Comment by qazip** [comment]
@overdodactyl , that link you provided doesn't seem to exist. How does one apply the dark theme to web-extensions?
