### ISSUE TITLE
Unreadable search bars

### ISSUE THREAD

**Issue by DukeValentine** [overdodactyl/ShadowFox#75]
When using a search bar in some websites, the suggested items appear as grey(no font contrast) unless I hover over the item, like this: https://streamable.com/r38la

**Comment by overdodactyl** [comment]
Hmm that's not good!

Can you link me to some sites you're noticing that on?

**Comment by DukeValentine** [comment]
Reddit and github are some of them. 

I tried replacing the userChrome.css with one from another similar project (I kept the userContent.css as is) and the issue was not present, so I guess the problem is in userChrome.css.

**Comment by overdodactyl** [comment]
Probably a silly question, but I'm not seeing any drop downs on those sites, could you link a page?

**Comment by DukeValentine** [comment]
Well, at github the drop down would be the search bar at the top.
Anyway, I managed to fix the issue by copying the parts I thought would be relevant of that other userChrome.css.
```
`/* This changes the autocomplete popup borders */
#PopupAutoCompleteRichResult, #PopupSearchAutoComplete, #PopupAutoComplete
{border: 1px solid #000 !important}`

`/* This changes the autocomplete background color of the URL bar */
.autocomplete-richlistbox,
/* Changes the color of searchbox  old searches (Continues from above) */
.search-panel-tree {background-color: #444 !important}
`
/* Changes the color of the highlighted item (only the selected one) on the url and searchbar */
.autocomplete-richlistitem[selected="true"], 
.search-panel-tree > .autocomplete-treebody::-moz-tree-cell(fromhistory, selected)
{background-color: #25a !important}

/* Changes the color of the autocomplete on the URL bar */
#PopupAutoCompleteRichResult .ac-title-text,
#PopupAutoCompleteRichResult .ac-tags-text,
#PopupAutoCompleteRichResult .ac-action-text,

/* Changes the color of the autocomplete on web area inputs (Continues from above) */
.autocomplete-richlistbox .ac-action-text, 
.autocomplete-richlistbox .ac-tags-text,
.autocomplete-richlistbox .ac-title-text,

/* Changes the color of search old searches (Continues from above) */
.search-panel-tree 
{color: #ccc !important}

/* The search autocomplete "-" lines */
.ac-separator {color: #222 !important}

/* Changes the color of the autocomplete links on the URL bar */
#PopupAutoCompleteRichResult .ac-url-text {color: rgb(0,160,200) !important}

/* Changes the color of header of the search option */
.search-panel-header, .addengine-item {
  background-color: #333 !important;
  color: #ccc !important}

/* Changes the color of the "Add x new search engine" hover effect */
.addengine-item:hover {background-color: #444 !important}

/* Changes the color of search engines choices */
.search-panel-one-offs {background: linear-gradient(#337,#115) !important}

/* Changes the color of search engine options button */
.search-setting-button {
    background: linear-gradient(#333,#111) !important;
    color: #777 !important}
.search-setting-button:hover {background: linear-gradient(#111,#333) !important}

/* Changes the color of searched item on the search popup */
.search-panel-input-value {color: #0FF !important}`
```

**Comment by overdodactyl** [comment]
That was silly of me.  I wasn't seeing any drop downs because I had made an `about:config` tweak.  

Looks like I may have just needed to increase the specificity of my changes to the address bar drop down so they weren't being applied to webpages.
 
New profile:

![screen shot 1](https://user-images.githubusercontent.com/33071129/36912120-abc6c8f2-1e3d-11e8-8132-e66ae0c65199.png)

ShadowFox before changes:

![screen shot 2](https://user-images.githubusercontent.com/33071129/36912138-bb9cfaee-1e3d-11e8-9c42-f60737457697.png)

ShadowFox after changes:

![screen shot 3](https://user-images.githubusercontent.com/33071129/36912155-c734c274-1e3d-11e8-80e4-f129e0117000.png)

The problem I was having didn't look quite identical to yours (the background of the drop down items looks white for me, not grey), so let me know if this doesn't fix what you were seeing.

**Comment by DukeValentine** [comment]
To apply the changes I just run the updater?

**Comment by overdodactyl** [comment]
Yep!

**Comment by DukeValentine** [comment]
The issue has been solved, the drop down items are following the browser gtk theme.

**Comment by overdodactyl** [comment]
>The issue has been solved

Sweet!  Thanks for reporting the issue.

>if I wanted to customize those drop down menus (different background and font color), what should I modify?

Try adding something to the effect of:

```css
.autocomplete-richlistbox {
  background-color: red !important;
  color: yellow !important;
}
```

to your `userChrome_customization.css` file inside of the `ShadowFox_customization` directory and re-running the updater script.

(fair warning: I didn't do any extensive testing - just ensured that applied to the Reddit and GitHub drop downs without effecting the address bar one)

**Comment by DukeValentine** [comment]
If I understood correctly if I there's an entry in the userChrome_customization.css file, like the '.autocomplete-richlistbox' one, it's going to overwrite what is in the userChrome.css file, correct?

Unrelated question, how do I use the internal UUIDs file?

**Comment by overdodactyl** [comment]
I still need to get better documentation on the updaters, but I think the info in #74 should answer most of your questions for now (particularly for the UUIDs).

`userChrome_customization.css` is appended to the very end of userChrome.css.  So if you have the same selector with a different attribute value, it will override ShadowFox.  CSS rules will always make something with more specificity apply, however.  So in the case above, since the address bar is more specific, it still applies there and your custome styling of `.autocomplete-richlistbox` will only go into effect in other places (such as webpages).

**Comment by DukeValentine** [comment]
Another question,how can I change the background and color of buttons in a page? 
![screenshot_20180304_215022](https://user-images.githubusercontent.com/25365649/36957257-ebd3a85e-2011-11e8-90b4-187a57c15fc7.png)

**Comment by overdodactyl** [comment]
Buttons will vary for every page, there isn't a universal selector for them.  To find the selectors, you can use Firefox's Inspector

**Comment by overdodactyl** [comment]
In the case above, I think you could add the following to your  `userContent_customization.css` file:

```css
@-moz-document url-prefix("https://addons.mozilla.org") {
    .Select {
        color: var(--grey-30) !important;
        background-color: var(--grey-50) !important;
    }
}
```

(didn't test)
