### ISSUE TITLE
Issues with Dark Mode options in about:addons

### ISSUE THREAD

**Issue by Dooogurt** [overdodactyl/ShadowFox#77]
![add-ons_manager_-_mozilla_firefox_2018-03-06_20-34-08](https://user-images.githubusercontent.com/10239012/37068729-17fe1870-217e-11e8-8b53-ef3ace73fa77.jpg)

Dark Mode
Extension in the AMO https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/
The text is unreadable while .css files are in use. Just changing the font color if possible would help tremendously.

**Comment by overdodactyl** [comment]
Hi @Dooogurt,

There's a fix currently available for Dark Mode.  See here:

https://github.com/overdodactyl/ShadowFox/wiki/Altering-webextensions

If you're using the updater scripts, you can simply add the UUID to the  `internal_UUIDs.txt` file that's created rather than going through the (now somewhat outdated) wiki steps.  Until I get better documentation up for it (I keep saying this, but I really will get this done either today or tomorrow), I think the comments/instructions in #74 should help.

That fixes the text, but I just noticed the text boxes aren't styled, so I'll get that done shortly.

**Comment by overdodactyl** [comment]
![dark_mode](https://user-images.githubusercontent.com/33071129/37070408-3d9b14bc-21af-11e8-9ade-e046ba0d9435.png)

Should be all good now 👍
