### ISSUE TITLE
background flaw in pageinfo

### ISSUE THREAD

**Issue by stonecrusher** [overdodactyl/ShadowFox#92]
The screenshot should be quite self explanatory. Please change the background-color of `caption`.
![screenshot](https://user-images.githubusercontent.com/1388389/37332524-3a5d99da-26a7-11e8-8c48-dfd9c18559a0.PNG)

**Comment by overdodactyl** [comment]
I think these should be taken care of by the following lines:

https://github.com/overdodactyl/ShadowFox/blob/master/css/userChrome-files/page_info.css#L101-L112

They are behind an `@media` statement though, which there was a [bug in FF 58](https://github.com/overdodactyl/ShadowFox/wiki/Known-Problems#styling-for-specific-oss-not-going-into-effect) that prevented these from working.

FF 59 comes out today though, so once you update to that let me know if it's still a problem (you could also try using the windows specific userChrome file...but that will be removed from the repo soonish since it was just a workaround for the bug mentioned above)

**Comment by stonecrusher** [comment]
FF59 with latest page_info.css didn't work for me :-/
![screenshot 95](https://user-images.githubusercontent.com/1388389/37374078-c0b5936c-2719-11e8-9df7-7e26cb1b9123.png)

Using Windows fixed version made it worse:
![screenshot 94](https://user-images.githubusercontent.com/1388389/37374108-cfc52a02-2719-11e8-86b8-ba9222f0a567.png)

Maybe the reason is I am using Windows 8.1 ...

**Comment by overdodactyl** [comment]
Yikes...the windows one does look bad. Let's just forget about that one (probably will delete it from the repo shortly).

Try updating, I think the mistake was I used the wrong variable in line 109 above.

**Comment by stonecrusher** [comment]
Works now!
